#!/usr/bin/node
// require built-ins
var daemon = require('./lib/daemonize/daemonize').setup({ main:'server.js', name:'armeria', pidfile:'armeria.pid'});

var arg = process.argv[2] || false;

switch(arg) {
    case 'start':
        daemon.start();
        break;
    case 'stop':
        daemon.stop();
        break;
    case 'restart':
        daemon.stop(function(err) {
            daemon.start();
        });
        break;
    case 'nodaemon':
        require('./server.js');
        break;
    case 'debug':
        process.kill(process.pid, 'SIGUSR1');
        require('./server.js');
        break;
    case 'status':
        var pid = daemon.status();
        if (pid)
            console.log("Daemon running. PID: " + pid);
        else
            console.log("Daemon is not running.");
        break;
    default:
        console.log('Valid options:');
        console.log('Syntax: ./app [option] [flags]');
        console.log('Choices for [option]:');
        console.log('   start    - start the server');
        console.log('   stop     - stop the server');
        console.log('   restart  - restart (or start) the server');
        console.log('   status   - check status of daemon');
        console.log('   nodaemon - start the server without using a daemon');
        console.log('   debug    - start the server in debug mode without using a daemon');
        console.log('Choices for [flags]:');
        console.log('   --live   - indicate this server is running on the live vps');
}